import {
  CodeCircle,
  HambergerMenu,
  CloseSquare,
  ExportSquare,
  MagicStar,
  ArrowRight2,
  Sms,
  Monitor,
  MobileProgramming,
  Data,
  CloudConnection,
  ShieldTick,
  Hierarchy3,
  Diagram,
  Briefcase,
  SearchNormal1,
  NoteText,
  Code1,
  Send2,
  TrendUp,
  Star1,
  Global,
  ArrowLeft2,
  CallCalling,
  Whatsapp,
  Link21,
} from 'iconsax-react'

export const Icons = {
  brand: CodeCircle,
  menu: HambergerMenu,
  close: CloseSquare,
  export: ExportSquare,
  spark: MagicStar,
  arrowRight: ArrowRight2,
  arrowLeft: ArrowLeft2,
  mail: Sms,
  web: Monitor,
  mobile: MobileProgramming,
  backend: Data,
  deploy: CloudConnection,
  shield: ShieldTick,
  stack: Hierarchy3,
  scale: Diagram,
  business: Briefcase,
  discover: SearchNormal1,
  plan: NoteText,
  build: Code1,
  launch: Send2,
  improve: TrendUp,
  star: Star1,
  global: Global,
  call: CallCalling,
  whatsapp: Whatsapp,
  link: Link21,
} as const
